#!/bin/bash

FILENAME=$0
ARGS=${@:2}
DC="docker compose"

CONTAINER_NAME="app"

case $1 in
"up")
    $DC up $ARGS
    ;;
"down")
    $DC down
    ;;
"build")
    $DC build $ARGS
    ;;
"shell")
    $DC exec $CONTAINER_NAME bash
    ;;
*)
    exit 1
    ;;
esac